// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalTranslator.Database;

#nullable disable

namespace MinimalTranslator.Database.Migrations
{
    [DbContext(typeof(InMemoryContext))]
    [Migration("20240531123543_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MinimalTranslator.Domain.Translations.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageTo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageFrom")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "LanguageTo");

                    b.ToTable("Translations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
