# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  translator:
    image: minimaltranslator
    container_name: minimaltranslator-api
    build:
      context: .
      dockerfile: src/MinimalTranslator.Api/Dockerfile
    ports:
      - 8080:8080